In [6]:
#Write a Python program to convert an array to an ordinary list with the same items. we can use the np.tolist() function
import numpy as np
array=np.random.randint(1, 5, size=(2,5))
print(array)
print(array.tolist())

[[3 3 2 1 3]
 [3 2 3 4 1]]
[[3, 3, 2, 1, 3], [3, 2, 3, 4, 1]]


In [4]:
#Write a NumPy program to compute the sum of the diagonal elements of a given array.
#Hint: Two methods to solve this problem: 1. manually(without direct function). 2. using the trace function
import numpy as np
random_array1 = np.random.randint(1, 5, size=(3,3))
print("the array is >" , random_array1)
trace_sum =  np.trace(random_array1)
print("1st method ya diaaaaaaa > ", random_array1[0,0] + random_array1[1,1] + random_array1[2,2])
print("2nd method ya diaaaaaaa > ", trace_sum)
# no third method ya diaaaaaaa

the array is > [[4 2 3]
 [1 3 2]
 [1 4 1]]
1st method ya diaaaaaaa >  8
2nd method ya diaaaaaaa >  8


In [9]:
#Given an array of your choice, get all the values higher than X :
#if a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2. 
my_amazing_array = np.random.randint(10, 30, size=(2,4))
print("my_amazing_array is : " , my_amazing_array)
x = 15
print("Values bigger than x =", my_amazing_array[my_amazing_array>x])

my_amazing_array is :  [[14 14 28 25]
 [27 10 22 10]]
Values bigger than x = [28 25 27 22]


In [12]:
#Given two arrays, A & B have the same shape. 
#The task is to apply addition by hand: C is the new array.
A = np.random.randint(1, 5, size=(2,3))
B = np.random.randint(1, 5, size=(2,3))
C = A + B #I hope that is what "by hand" means
print("A = ", A)
print("B = ", B)
print("Addition = ", C)

A =  [[4 1 3]
 [2 1 4]]
B =  [[3 1 4]
 [4 4 2]]
Addition =  [[7 2 7]
 [6 5 6]]


In [25]:
#Write a NumPy program to subtract the mean of each row of a given matrix.
#Hint: use the mean function
random_array = np.random.randint(1, 5, size=(3,3))
print("random_array = " , random_array)
print("random_array Mean = ", np.mean(random_array))
print("1st row Mean = ", np.mean(random_array[0]))
print("2nd row Mean = ", np.mean(random_array[1]))
print("3rd row Mean = ", np.mean(random_array[2])) #Glad u didn't ask about coulumns

random_array =  [[3 3 4]
 [1 3 4]
 [2 2 3]]
random_array Mean =  2.7777777777777777
1st row Mean =  3.3333333333333335
2nd row Mean =  2.6666666666666665
3rd row Mean =  2.3333333333333335
